name: Vue build and update stats

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-update:
    name: Build and update stats
    runs-on: ubuntu-latest
    env:
      build: ${{ !contains(github.event.head_commit.message, 'Scheduled stats update') }}
    steps:
    - name: Clone repository
      run: "git clone https://${{ secrets.GH_PERSONAL_TOKEN }}@github.com/encap/coderush.git ."
    - name: Setup Node.js
      if: env.build
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Run npm install
      if: env.build
      run: npm install
    - name: Vue build
      if: env.build
      run: npm run build
    - name: Configure git
      run: |
        git config --global credential.helper cache
        git config --global user.email "bot@github.com"
        git config --global user.name "Bot"
    - name: Stage files
      run: |
        git add -f server/ dist/
        git commit --allow-empty -m 'post-buid temp commit'
    - name: Switch to deploy branch
      run: git checkout deploy
    - name: Prepare for commit
      run: |
        rm -r server/ dist/
        git checkout master -- "server/" "dist/"
    - name: Commit build
      if: env.build
      run: git commit --allow-empty -m 'Automatic deploy'
    - name: Commit stats update
      if: ${{ !env.build }}
      run: git commit -m 'Scheduled stats update'
    - name: Push for deployment
      run: git push