name: Deploy to CDN

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  upload-assets:
    name: Upload Assets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT_ID }}
        export_default_credentials: true
    - name: Upload
      run: |-
        gsutil -m rsync -r dist gs://$GCS_BUCKET
      env:
        GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
        
