name: Handle New Stats

on:
  repository_dispatch:
    types: update-stats
  workflow_dispatch:

jobs:
  update-stats:
    name: Update Stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Process update
      run: |
        node actions/process-stats-update.js
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic stats update
        commit_user_name: Update Stats Action
        commit_user_email: bot@github.com
        commit_author: Bot <bot@github.com>
        
